swiftlint_version: 0.54.0

parent_config: https://raw.githubusercontent.com/Automattic/swiftlint-config/0f8ab6388bd8d15a04391825ab125f80cfb90704/.swiftlint.yml
remote_timeout: 10.0

excluded:
  - Modules/.build

opt_in_rules:
  - discarded_notification_center_observer
  - duplicate_imports
  - overridden_super_call
  - shorthand_optional_binding
  - vertical_whitespace
  - weak_delegate

overridden_super_call:
  severity: error

discarded_notification_center_observer:
  severity: error

weak_delegate:
  severity: error
